version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

submodules:
   include: all

# Explicitly set the version of Python and its requirements
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
