defaults:
  - base_rl_config
  - _self_

device: auto
project_dir: ./projects/output/rl/highway_lane_rep
scenario_dir: ./data/highd-sample/
seed: 0
warmstart: False
profile: False

training: 
  wandb_logging: True
  checkpoint_freq: 50000
  eval_freq: 10
  gradient_save_freq: 1
  log_freq: 1
  n_envs: 1
  n_eval_episodes: 10
  normalize_observations: False
  normalize_rewards: False
  normalize_rewards_threshold: 10.0
  record_backoff: 1.0
  video_frequency: 10000
  total_timesteps: 10_000_000
  verbose: 0
  video_length: 500

experiment: 
  model_path: ./projects/graph_rl_agents/highway_lane_rep/model.pt
  data_padding_size: 2000
  virtual_lanelet_length: &virtual_lanelet_length 100.0
  ego_map_radius: 50.0 
  render_on_step: False
  render_debug_overlays: True
  hd_videos: False
  enable_representations: &enable_representations True
  enable_decoding: True
  raise_exceptions: False
  linear_lanelet_projection: True
  spawning:
    min_goal_distance: 100.0
    min_vehicle_distance: 8.0

model: 
  gae_lambda: 0.8
  gamma: 0.99
  n_epochs: 8
  ent_coef: 1e-2
  n_steps: 256
  batch_size: 32
  vf_coef: 0.5
  max_grad_norm: 10.0
  learning_rate: 5e-4
  clip_range: 0.2
  gnn_out_dim: 80representations
  gnn_hidden_dim: 80
  gnn_layers: 3
  enable_representations: *enable_representations
