#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

# Theme requires:
# pip install sphinx_rtd_theme

import os
import sys

root_dir = os.path.abspath('../')
package_dir = os.path.abspath('../crgeo')
sys.path.insert(0, root_dir)
sys.path.insert(0, package_dir)
print("root_dir:", root_dir)
print("package_dir:", package_dir)

# from pip import _internal
# print(_internal.main(['list']))
for x in os.walk(package_dir):
  sys.path.insert(0, x[0])
  print("Extra path", x[0])
print("sys.path:", '\n'.join(sys.path))


# -- General configuration --------------------------------------------------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.coverage',
    'sphinx.ext.napoleon',  # numpy style docstrings
    'sphinx.ext.intersphinx',
    'sphinxcontrib.video'
]



# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'CommonRoad_Geometric'
copyright = '2022, Eivind Meyer'
author = 'Eivind Meyer, Maurice Brenner, Bowen Zhang'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '2023.1'
# The full version, including alpha/beta/rc tags.
release = '2023.1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

autodoc_mock_imports = [
    "PIL",
    "commonroad",
    "commonroad_dc",
    "commonroad_route_planner",
    "dill",
    "geopy",
    "pandas",
    "pyglet",
    "scipy",
    "shapely",
    "sklearn",
    "sumolib"
    "tqdm",
    "traci",
    "typing_extensions",
]

os.environ["PYTORCH_JIT"] = "0"


# -- Options for HTML output ------------------------------------------------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'classic'
html_theme = "sphinx_rtd_theme" #pip install sphinx_rtd_theme

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#

html_theme_options = {
    'canonical_url': '',
    'analytics_id': '',
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    # Toc options
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

html_logo = 'img/logo.png'


# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
# html_sidebars = {
#     '**': [
#        'about.html',
#         'navigation.html',
#         'relations.html',  # needs 'show_related': True theme option to display
#         'searchbox.html',
#         'donate.html',
#     ]
# }


# -- Options for HTMLHelp output ----------------------------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'commonroad_geometricdoc'


# -- Options for LaTeX output -----------------------------------------------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'crgeo.tex', 'crgeo Documentation',
     'Eivind Meyer', 'manual'),
]


# -- Options for manual page output -------------------------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'crgeo', 'crgeo Documentation',
     [author], 1)
]


# -- Options for Texinfo output -----------------------------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'crgeo', 'crgeo Documentation',
     author, 'crgeo', 'One line description of project.',
     'Miscellaneous'),
]
