defaults:
  - base_geometric_config
  - _self_

project_dir: ./projects/output/geometric/lane_occupancy
seed: 0
no_wandb: False
warmstart: False
device: auto
profile: True

dataset: 
  train_scenario_dir: &scenario_dir ./data/osm_recordings/
  test_scenario_dir: *scenario_dir
  val_scenario_dir: *scenario_dir
  overwrite: False
  pre_transform_workers: 1
  cache_data: False
  max_samples_per_scenario: 100
  max_scenarios: 1

experiment: 
  time_horizon: 60
  min_occupancy_ratio: 0.0

training: 
  backward_freq: 1
  batch_size: 16
  checkpoint_frequency: 100
  early_stopping: 
  enable_multi_gpu: False
  enable_rendering: True
  gradient_clipping_threshold: 
  log_freq: 100
  max_epochs: 10000
  max_optimize_samples: 1
  overfit: False
  swallow_errors: False
  test_freq: 1
  test_split: 0.1
  validate_inner: True
  validation_freq:  1
  validation_split:  1
  verbose: 1
  video_freq: 1000
  video_length: 400
  video_record_backoff: 1.5
